config/routes.rb
Rails.application.routes.draw do
  resources :restaurants
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  CATEGORY = %w(chinese italian japanese french belgian).freeze
  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: CATEGORY }
 end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, length: { minimum: 0 }
  validates :rating, length: { maximum: 5 }
  validates :rating, inclusion: { in: 0..5 }
  validates :rating, numericality: { only_integer: true }
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path, status: :see_other
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :category, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
<ul>
<% @restaurants.each do |restaurant| %>
 <li> <%= link_to restaurant.name, restaurant_path(restaurant) %> </li>
 <%= link_to "Delete",
  restaurant_path(restaurant),
  data: {turbo_method: :delete}%>
<% end %>
</ul>
<%= link_to '+ Add a new restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<%= form_with model: @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :category %>
  <%= f.text_field :category %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.submit %>
<% end %>

<%= link_to "back to list", restaurants_path %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p> You can find us at: <%= @restaurant.address %> </p>
<p> Come check our <%= @restaurant.category %> cuisine out!</p>

<%= link_to "Back to list of restaurants", restaurants_path %>